### ISSUE TITLE
Deleting Gists broken

### ISSUE THREAD

**Issue by moggoly** [cmoulton/grokSwiftREST_v1.1#2]
When deleting my gists, the following code fails:

``` swift
let gistToDelete = gists.removeAtIndex(indexPath.row)
tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Fade)
// delete from API
if let id = gists[indexPath.row].id {
    ...
}
```

because we are first removing the gist from the gists array, then attempting to access it again to get it's id. The line getting the id should read:

``` swift
if let id = gistToDelete.id {
```

**Comment by cmoulton** [comment]
Fixed in d07d81861efd0f3002e6f2ffe63f43828f164850
